version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/app
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 1000
      runas: root
